name: C++ Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ${{matrix.os-type}}
    
    strategy:
      matrix:
        os-type: [ubuntu-latest]
        configuration: [Release]    
    
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt update
        sudo apt install build-essential g++
    - name: Configure
      working-directory: ${{github.workspace}}/src/cpp
      run: cmake -B ${{github.workspace}}/src/cpp/Build -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    - name: Build
      working-directory: ${{github.workspace}}/src/cpp
      run: cmake --build ${{github.workspace}}/src/cpp/Build --config ${{matrix.configuration}}
    - name: Test
      working-directory: ${{github.workspace}}/src/cpp/Build
      run: ctest -VV -C ${{matrix.configuration}} -L web-ifc
