name: Integratation Tests
env:
   NPM_TOKEN: ' '
on: 
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v14
      with:
          version: 3.1.44
    - uses: oven-sh/setup-bun@v1
        with:
        bun-version: latest
    - name: Install modules
      run: |
        bun i
        npm i
    - name: Build
      run: bun run build-release
    - uses: actions/setup-node@v4
    - name: Run all tests
      run: npm t
    - name: Regression Tests
      run: bun run regression